# Generated by Django 4.1.2 on 2022-10-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('login', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('avatar', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.IntegerField()),
                ('title_question', models.CharField(max_length=256)),
                ('text_question', models.TextField()),
                ('counting_likes', models.IntegerField()),
                ('counting_answers', models.IntegerField()),
                ('id_author_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=256)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField()),
                ('correct', models.BooleanField()),
                ('id_author_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
    ]
